update=16/04/2019 06:37:03
version=1
last_client=kicad
[general]
version=1
RootSch=
BoardNm=
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=
[eeschema/libraries]
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceAjustPassiveValues=0
LabSize=50
ERC_TestSimilarLabels=1
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=PIC18F4550 dev board.net
CopperLayerCount=2
BoardThickness=1.6
AllowMicroVias=0
AllowBlindVias=0
RequireCourtyardDefinitions=0
ProhibitOverlappingCourtyards=0
MinTrackWidth=0.01
MinViaDiameter=0.45
MinViaDrill=0.2
MinMicroViaDiameter=0.45
MinMicroViaDrill=0.2
MinHoleToHole=0.127
TrackWidth1=0.25
TrackWidth2=0.4
TrackWidth3=1
ViaDiameter1=0.8
ViaDrill1=0.4
ViaDiameter2=0.8
ViaDrill2=0.4
ViaDiameter3=0.9
ViaDrill3=0.6
dPairWidth1=0.2
dPairGap1=0.25
dPairViaGap1=0.25
SilkLineWidth=0.15
SilkTextSizeV=1
SilkTextSizeH=1
SilkTextSizeThickness=0.15
SilkTextItalic=0
SilkTextUpright=1
CopperLineWidth=0.2
CopperTextSizeV=1.5
CopperTextSizeH=1.5
CopperTextThickness=0.3
CopperTextItalic=0
CopperTextUpright=1
EdgeCutLineWidth=0.15
CourtyardLineWidth=0.05
OthersLineWidth=0.15
OthersTextSizeV=1
OthersTextSizeH=1
OthersTextSizeThickness=0.15
OthersTextItalic=0
OthersTextUpright=1
SolderMaskClearance=0.051
SolderMaskMinWidth=0.25
SolderPasteClearance=0
SolderPasteRatio=-0
[pcbnew/Layer.F.Cu]
Name=F.Cu
Type=2
[pcbnew/Layer.B.Cu]
Name=B.Cu
Type=2
[pcbnew/Netclasses]
[pcbnew/Netclasses/1]
Name=Power
Clearance=0.03
TrackWidth=1
ViaDiameter=1.2
ViaDrill=0.7
uViaDiameter=0.508
uViaDrill=0.2
dPairWidth=0.3
dPairGap=0.6
dPairViaGap=0.25
[pcbnew/Netclasses/2]
Name=Signal
Clearance=0.0254
TrackWidth=0.4
ViaDiameter=0.8
ViaDrill=0.4
uViaDiameter=0.508
uViaDrill=0.2
dPairWidth=0.254
dPairGap=0.4
dPairViaGap=0.25
